name: scan-build-push-ecr
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
  push:
    branches:
      - '**'
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  register-artifact:
    steps:
      - name: Get sourcecode
        uses: cloudbees-io/checkout@v1
      - id: build
        name: Test and Scan
        uses: calculi-corp/cb-internal-shared-actions/build@v8
        with:
          golangci-lint: "true"
          run-unit-test: "true"
          unit-test-percent: "80"
          create-slsa-attestation: "false"
      - name: register build
        uses: cloudbees.io/register-build-artifact
        with:
          cloudbees-url: https://api.saas-preprod.beescloud.com
          name: dummy-go-gha
          version: 0.0.1
          url: https://example.test/dummy-go-gha/0.0.1/dummy-go-gha-action
      - name: register deployment
        uses: cloudbees.io/register-deployed-artifact
        with:
          cloudbees-url: https://api.saas-preprod.beescloud.com
          target-environment: pere-test
          url: https://example.test/dummy-go-gha/0.0.1/dummy-go-gha-action