name: scan-build-push-ecr
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
  push:
    branches:
      - "**"
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  register-artifact:
    steps:
      - name: Get sourcecode
        uses: cloudbees-io/checkout@v1
      - name: register build
        kind: build
        uses: cloudbees-io/register-build-artifact@v2
        with:
          cloudbees-url: https://api.saas-preprod.beescloud.com
          version: 0.0.1
          url: https://example.test/dummy-go-gha/0.0.1/dummy-go-gha-action
          action-name: dummy-go-gha